# Practical Exam: House sales

RealAgents is a real estate company that focuses on selling houses.

RealAgents sells a variety of types of house in one metropolitan area.

Some houses sell slowly and sometimes require lowering the price in order to find a buyer.

In order to stay competitive, RealAgents would like to optimize the listing prices of the houses it is trying to sell.

They want to do this by predicting the sale price of a house given its characteristics.

If they can predict the sale price in advance, they can decrease the time to sale.


## Data

The dataset contains records of previous houses sold in the area.

| Column Name | Criteria                                                |
|-------------|---------------------------------------------------------|
| house_id    | Nominal. </br> Unique identifier for houses. </br>Missing values not possible. |
| city        | Nominal. </br>The city in which the house is located. One of 'Silvertown', 'Riverford', 'Teasdale' and 'Poppleton'. </br>Replace missing values with "Unknown". |
| sale_price  | Discrete. </br>The sale price of the house in whole dollars. Values can be any positive number greater than or equal to zero.</br>Remove missing entries. |
| sale_date   | Discrete. </br>The date of the last sale of the house. </br>Replace missing values with 2023-01-01. |
| months_listed  | Continuous. </br>The number of months the house was listed on the market prior to its last sale, rounded to one decimal place. </br>Replace missing values with mean number of months listed, to one decimal place. |
| bedrooms    | Discrete. </br>The number of bedrooms in the house. Any positive values greater than or equal to zero. </br>Replace missing values with the mean number of bedrooms, rounded to the nearest integer. |
| house_type   | Ordinal. </br>One of "Terraced" (two shared walls), "Semi-detached" (one shared wall), or "Detached" (no shared walls). </br>Replace missing values with the most common house type. |
| area      | Continuous. </br>The area of the house in square meters, rounded to one decimal place. </br>Replace missing values with the mean, to one decimal place. |

In [30]:
import pandas as pd

# Load the dataset
df = pd.read_csv("house_sales.csv")

In [31]:
df.head(20)

    house_id        city  sale_price  ... bedrooms     house_type         area
0    1217792  Silvertown       55943  ...        2  Semi-detached  107.8 sq.m.
1    1900913  Silvertown      384677  ...        5       Detached  498.8 sq.m.
2    1174927   Riverford      281707  ...        6       Detached  542.5 sq.m.
3    1773666  Silvertown      373251  ...        6           Det.  528.4 sq.m.
4    1258487  Silvertown      328885  ...        5       Detached  477.1 sq.m.
5    1539789   Riverford       47143  ...        2  Semi-detached  123.2 sq.m.
6    1353069    Teasdale      429914  ...        6       Detached  544.6 sq.m.
7    1155864    Teasdale      284440  ...        4       Detached  371.3 sq.m.
8    1608726    Teasdale       87134  ...        2  Semi-detached  125.7 sq.m.
9    1358764   Poppleton      211203  ...        4       Detached  371.5 sq.m.
10   1277089    Teasdale      382655  ...        5       Detached  428.8 sq.m.
11   1117876   Riverford       54934  ...        2  Semi-detached  147.7 sq.m.
12   1710056  Silvertown      297101  ...        4       Detached  395.6 sq.m.
13   1860591   Poppleton      171502  ...        4       Detached  304.4 sq.m.
14   1470021   Riverford      158198  ...        4       Detached  316.8 sq.m.
15   1396614    Teasdale      428808  ...        6       Detached  554.3 sq.m.
16   1369220    Teasdale      269688  ...        4       Detached  374.9 sq.m.
17   1195530  Silvertown      208965  ...        3       Detached  294.3 sq.m.
18   1384054  Silvertown      257146  ...        4       Detached  397.0 sq.m.
19   1070852   Riverford      160653  ...        4       Detached  316.3 sq.m.

[20 rows x 8 columns]

In [32]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   house_id       1500 non-null   int64
 1   city           1500 non-null   object
 2   sale_price     1500 non-null   int64
 3   sale_date      1500 non-null   object
 4   months_listed  1469 non-null   float64
 5   bedrooms       1500 non-null   int64
 6   house_type     1500 non-null   object
 7   area           1500 non-null   object
dtypes: float64(1), int64(3), object(4)
memory usage: 93.9+ KB
None

In [33]:
for col in df.columns:
    unique_vals = df[col].unique()
    print(f"\n➡ {col} ({len(unique_vals)} unique values):")
    print(unique_vals)

➡ house_id (1500 unique values):
[1217792 1900913 1174927 ... 1058161 1822037 1679272]

➡ city (5 unique values):
['Silvertown' 'Riverford' 'Teasdale' 'Poppleton' '--']

➡ sale_price (1499 unique values):
[ 55943 384677 281707 ... 176612 197827 162099]

➡ sale_date (817 unique values):
['2021-09-12' '2021-01-17' '2021-11-10' '2020-04-13' '2020-09-24'
 '2020-09-25' '2021-05-18' '2020-10-15' '2021-01-07' '2020-05-04'
 '2021-10-26' '2020-06-11' '2022-10-10' '2021-08-04' '2020-08-18'
 '2021-07-18' '2020-11-23' '2020-06-05' '2020-11-19' '2020-02-25'
 '2020-04-16' '2020-01-14' '2022-12-28' '2020-04-07' '2020-01-09'
 '2021-08-29' '2022-05-20' '2021-12-13' '2020-10-27' '2022-08-22'
 '2022-11-14' '2021-04-02' '2020-01-31' '2020-09-29' '2022-09-05'
 '2020-07-23' '2020-10-14' '2020-08-03' '2020-07-05' '2022-04-03'
 '2022-01-14' '2021-03-19' '2022-04-29' '2022-10-16' '2022-08-02'
 '2021-09-30' '2021-09-07' '2022-07-30' '2022-01-03' '2020-12-27'
 '2020-06-15' '2022-09-07' '2022-09-17' '2022-09-23' '2021-06-05'
 '2022-08-06' '2022-05-10' '2021-02-28' '2020-06-27' '2020-10-06'
 '2022-12-18' '2021-12-22' '2022-12-19' '2021-07-31' '2020-09-28'
 '2022-05-16' '2022-10-02' '2021-05-23' '2020-11-13' '2020-03-08'
 '2021-11-06' '2022-02-04' '2020-06-04' '2022-10-03' '2021-04-20'
 '2022-02-25' '2020-06-18' '2020-05-28' '2020-12-28' '2021-02-13'
 '2021-05-14' '2021-10-11' '2020-06-24' '2021-02-24' '2021-06-04'
 '2022-02-11' '2020-06-03' '2022-03-10' '2020-07-11' '2022-07-08'
 '2021-11-09' '2021-12-04' '2020-07-16' '2021-09-15' '2021-04-24'
 '2021-03-18' '2020-04-10' '2022-11-28' '2021-08-11' '2021-05-28'
 '2021-01-27' '2020-12-25' '2021-10-07' '2022-06-14' '2020-07-14'
 '2020-05-16' '2020-09-13' '2022-02-26' '2022-07-27' '2021-07-23'
 '2020-12-22' '2021-06-06' '2021-01-09' '2022-10-05' '2020-02-07'
 '2022-02-22' '2021-01-19' '2021-02-20' '2020-01-17' '2021-04-30'
 '2021-07-04' '2021-08-06' '2020-11-26' '2022-12-10' '2020-11-06'
 '2022-05-18' '2022-08-03' '2020-02-13' '2021-08-14' '2020-06-09'
 '2021-02-19' '2020-01-10' '2022-09-21' '2022-12-21' '2021-01-10'
 '2021-09-16' '2020-01-07' '2020-06-29' '2022-01-08' '2020-01-22'
 '2020-07-27' '2022-10-14' '2020-10-08' '2020-10-07' '2022-04-04'
 '2022-02-23' '2022-06-20' '2022-07-12' '2022-01-10' '2022-02-10'
 '2022-04-16' '2020-01-15' '2021-02-14' '2022-04-09' '2021-03-01'
 '2020-09-08' '2022-07-20' '2020-10-01' '2020-12-14' '2021-08-30'
 '2020-04-12' '2020-01-16' '2022-11-26' '2020-08-09' '2022-12-16'
 '2021-12-24' '2022-03-29' '2021-04-17' '2021-10-12' '2022-03-03'
 '2022-09-02' '2021-08-28' '2021-08-18' '2021-03-13' '2022-07-19'
 '2020-04-23' '2022-01-17' '2022-03-14' '2022-09-30' '2022-01-20'
 '2022-06-18' '2021-06-25' '2022-06-15' '2022-01-25' '2021-07-15'
 '2021-09-24' '2021-03-09' '2020-11-10' '2021-12-21' '2020-06-28'
 '2021-03-14' '2020-02-20' '2022-08-05' '2020-02-15' '2021-04-27'
 '2022-05-05' '2022-11-13' '2020-08-10' '2022-12-13' '2021-11-26'
 '2022-12-29' '2021-10-18' '2020-07-30' '2022-10-17' '2022-06-10'
 '2021-02-07' '2021-01-22' '2020-08-20' '2021-01-25' '2022-10-01'
 '2022-08-07' '2022-08-18' '2021-05-10' '2020-03-22' '2021-06-03'
 '2022-12-11' '2021-11-24' '2022-12-01' '2022-12-05' '2020-02-09'
 '2021-01-05' '2021-02-25' '2022-09-26' '2020-03-15' '2021-01-16'
 '2022-11-23' '2020-05-17' '2021-12-07' '2020-08-15' '2021-10-30'
 '2021-05-24' '2022-01-05' '2021-12-09' '2021-07-10' '2020-04-29'
 '2020-11-14' '2022-03-07' '2020-02-19' '2020-03-24' '2021-11-01'
 '2021-05-13' '2022-06-28' '2020-09-16' '2021-06-14' '2021-05-17'
 '2020-01-12' '2021-08-21' '2022-09-15' '2021-11-12' '2021-02-04'
 '2021-12-01' '2021-03-20' '2022-11-07' '2022-09-28' '2022-05-26'
 '2022-10-24' '2021-07-11' '2020-03-27' '2022-01-12' '2022-06-17'
 '2020-04-30' '2022-10-04' '2021-01-20' '2020-03-17' '2020-07-22'
 '2022-11-12' '2020-03-09' '2022-12-30' '2021-10-21' '2021-12-11'
 '2022-07-28' '2021-08-23' '2022-12-22' '2022-07-16' '2020-05-15'
 '2020-12-31' '2022-10-18' '2022-08-30' '2022-09-29' '2020-08-06'
 '2022-05-13' '2020-06-14' '2021-09-13' '2020-04-08' '2022-06-08'
 '2020-02-08' '2021-07-07' '2022-05-04' '2020-07-06' '2021-09-08'
 '2021-04-11' '2021-11-21' '2021-08-31' '2020-10-16' '2022-12-24'
 '2021-03-31' '2021-05-01' '2021-01-21' '2020-05-10' '2020-04-05'
 '2020-04-17' '2020-03-06' '2022-09-01' '2020-02-12' '2020-08-25'
 '2021-12-23' '2021-08-05' '2020-05-07' '2022-05-02' '2020-07-12'
 '2020-01-27' '2020-04-21' '2022-03-28' '2021-04-12' '2021-06-13'
 '2022-01-22' '2021-06-17' '2020-08-26' '2021-09-27' '2022-02-17'
 '2021-09-06' '2020-08-08' '2020-11-21' '2021-05-21' '2020-10-17'
 '2020-03-19' '2021-10-24' '2020-02-27' '2022-04-02' '2021-02-01'
 '2021-08-24' '2021-10-25' '2021-11-20' '2021-06-20' '2020-07-31'
 '2020-12-24' '2021-08-19' '2022-05-27' '2022-06-11' '2021-10-29'
 '2020-08-17' '2021-11-25' '2021-07-01' '2020-01-03' '2022-01-29'
 '2022-04-17' '2020-11-04' '2022-07-23' '2022-07-11' '2022-12-15'
 '2020-12-01' '2021-02-26' '2020-11-25' '2020-11-16' '2020-03-18'
 '2021-12-28' '2020-07-07' '2021-11-03' '2021-12-06' '2021-05-31'
 '2022-11-01' '2021-06-30' '2022-12-20' '2020-11-29' '2022-06-04'
 '2020-10-20' '2022-02-27' '2020-07-26' '2021-08-15' '2022-09-14'
 '2021-10-20' '2021-06-12' '2021-01-04' '2021-08-07' '2020-11-11'
 '2020-11-08' '2022-11-08' '2020-01-01' '2021-04-08' '2021-01-08'
 '2021-01-26' '2021-09-23' '2022-04-11' '2020-10-26' '2020-12-29'
 '2020-04-27' '2021-03-10' '2022-05-15' '2020-01-30' '2020-01-06'
 '2020-06-13' '2021-08-26' '2020-05-24' '2020-08-22' '2020-09-04'
 '2022-11-10' '2021-09-19' '2021-06-11' '2022-03-25' '2022-02-13'
 '2022-01-31' '2022-10-09' '2020-06-06' '2021-01-14' '2022-06-07'
 '2020-12-12' '2022-10-26' '2020-01-28' '2022-03-08' '2021-10-23'
 '2021-08-01' '2020-08-31' '2020-04-18' '2020-03-02' '2021-02-15'
 '2020-09-19' '2020-02-17' '2022-03-31' '2021-05-08' '2021-12-31'
 '2022-10-19' '2022-04-01' '2021-07-22' '2022-10-11' '2021-02-06'
 '2021-06-24' '2020-05-29' '2022-10-29' '2020-12-26' '2022-08-29'
 '2020-01-19' '2020-06-08' '2022-09-10' '2022-02-15' '2020-03-20'
 '2020-09-02' '2020-03-31' '2022-05-29' '2021-05-29' '2022-08-04'
 '2021-03-15' '2022-05-11' '2020-03-01' '2022-05-30' '2022-01-04'
 '2021-07-26' '2021-11-29' '2022-08-08' '2021-11-17' '2020-10-09'
 '2021-06-09' '2021-06-18' '2020-09-05' '2021-06-16' '2020-12-09'
 '2022-03-22' '2022-01-26' '2021-10-17' '2022-12-25' '2020-02-28'
 '2020-12-07' '2020-11-27' '2022-04-28' '2021-04-03' '2021-04-15'
 '2021-09-11' '2022-04-27' '2022-06-25' '2022-11-25' '2021-10-19'
 '2021-03-08' '2022-12-26' '2022-01-11' '2021-05-11' '2021-07-19'
 '2020-06-25' '2020-09-15' '2022-02-28' '2020-01-08' '2020-01-02'
 '2021-04-01' '2020-03-13' '2022-09-09' '2022-05-31' '2021-03-05'
 '2021-09-22' '2020-12-17' '2020-08-11' '2022-09-16' '2022-07-09'
 '2022-05-14' '2021-12-03' '2021-07-08' '2020-05-20' '2022-02-01'
 '2022-03-06' '2022-04-06' '2022-02-16' '2020-11-24' '2021-04-29'
 '2021-11-11' '2020-04-28' '2021-01-02' '2022-07-13' '2021-07-02'
 '2022-04-24' '2021-05-04' '2020-10-13' '2021-12-14' '2022-02-20'
 '2020-10-30' '2020-11-05' '2020-03-04' '2020-11-30' '2022-08-19'
 '2021-03-02' '2021-10-06' '2020-12-11' '2021-02-11' '2020-08-12'
 '2021-04-04' '2020-11-15' '2022-02-05' '2021-03-17' '2022-03-23'
 '2022-03-16' '2021-11-19' '2020-05-13' '2020-12-03' '2022-03-15'
 '2021-11-28' '2021-03-29' '2020-02-11' '2021-03-25' '2021-11-13'
 '2022-03-27' '2020-07-24' '2020-12-06' '2021-07-21' '2021-06-27'
 '2020-01-13' '2021-08-27' '2021-11-30' '2020-03-03' '2021-08-03'
 '2022-12-17' '2021-09-01' '2020-04-03' '2022-01-19' '2022-07-24'
 '2021-02-16' '2022-09-03' '2022-03-21' '2022-10-30' '2020-07-29'
 '2021-05-12' '2020-03-23' '2021-10-27' '2022-12-14' '2021-04-21'
 '2022-05-24' '2021-09-05' '2021-04-18' '2021-02-03' '2022-09-22'
 '2022-06-22' '2021-01-31' '2022-03-20' '2022-11-18' '2022-05-17'
 '2022-04-23' '2020-01-05' '2020-09-07' '2021-10-03' '2020-10-31'
 '2021-06-01' '2022-04-21' '2022-04-14' '2022-01-01' '2021-03-24'
 '2020-06-10' '2020-06-23' '2021-12-25' '2021-07-14' '2021-09-09'
 '2021-05-25' '2021-10-02' '2021-10-09' '2021-06-23' '2020-11-02'
 '2020-08-01' '2022-03-24' '2021-12-19' '2021-07-20' '2022-06-27'
 '2020-04-24' '2022-11-03' '2020-07-08' '2020-03-21' '2021-07-30'
 '2022-11-20' '2020-08-04' '2021-01-28' '2022-04-19' '2022-04-13'
 '2022-10-27' '2020-06-19' '2020-01-23' '2020-05-31' '2020-02-03'
 '2022-07-29' '2022-04-07' '2021-11-15' '2022-02-06' '2022-10-08'
 '2021-12-12' '2022-06-26' '2021-10-13' '2020-12-15' '2021-06-26'
 '2020-05-14' '2022-02-19' '2020-10-25' '2021-10-28' '2020-10-21'
 '2022-11-19' '2022-04-22' '2022-11-15' '2022-06-19' '2020-08-16'
 '2021-07-16' '2021-09-20' '2021-09-29' '2021-10-04' '2020-12-30'
 '2020-03-05' '2021-12-27' '2022-10-22' '2020-11-12' '2022-04-05'
 '2022-07-04' '2020-05-12' '2022-09-08' '2022-11-11' '2022-05-08'
 '2021-06-19' '2021-05-30' '2020-07-20' '2022-05-25' '2022-09-04'
 '2021-07-24' '2020-09-27' '2021-05-27' '2022-10-23' '2021-07-12'
 '2021-06-29' '2021-12-20' '2020-01-20' '2021-05-16' '2021-07-03'
 '2020-08-30' '2020-10-11' '2020-05-19' '2022-07-10' '2022-06-03'
 '2020-04-09' '2021-11-14' '2022-04-18' '2020-10-03' '2022-02-12'
 '2022-04-30' '2021-10-16' '2021-04-22' '2022-10-12' '2022-12-08'
 '2021-09-14' '2022-12-06' '2022-10-20' '2020-02-06' '2021-01-15'
 '2020-11-09' '2021-09-28' '2020-02-22' '2021-05-22' '2022-07-17'
 '2022-10-06' '2021-02-23' '2022-12-23' '2020-09-17' '2020-07-03'
 '2021-10-14' '2020-07-19' '2021-08-20' '2021-04-14' '2021-04-06'
 '2022-07-03' '2022-07-01' '2022-11-29' '2022-10-21' '2021-07-29'
 '2020-04-11' '2021-08-25' '2020-05-23' '2020-07-21' '2022-08-11'
 '2021-01-12' '2021-03-23' '2020-04-14' '2021-11-23' '2021-03-11'
 '2020-03-12' '2021-10-10' '2021-06-28' '2020-07-10' '2022-02-08'
 '2021-09-17' '2021-08-08' '2020-02-29' '2020-10-24' '2022-06-13'
 '2021-04-05' '2022-03-02' '2022-09-24' '2022-03-13' '2022-10-31'
 '2022-07-18' '2022-06-01' '2021-09-10' '2020-08-02' '2020-02-04'
 '2022-08-25' '2022-01-16' '2021-12-10' '2021-12-29' '2022-10-25'
 '2021-12-17' '2022-05-06' '2022-07-14' '2020-02-26' '2020-04-20'
 '2020-07-15' '2022-01-27' '2021-01-06' '2020-11-17' '2022-04-10'
 '2020-05-08' '2021-04-09' '2022-08-28' '2020-03-16' '2022-04-12'
 '2021-01-11' '2022-09-13' '2022-11-22' '2022-06-30' '2021-08-17'
 '2021-11-18' '2021-09-21' '2021-01-18' '2022-09-18' '2020-07-25'
 '2020-01-26' '2021-10-22' '2020-08-13' '2021-11-05' '2020-11-22'
 '2022-05-23' '2020-12-13' '2022-08-31' '2021-05-26' '2020-09-14'
 '2021-07-13' '2021-05-02' '2020-05-02' '2022-01-24' '2022-12-12'
 '2020-08-24' '2020-11-01' '2022-08-24' '2021-11-27' '2022-10-13'
 '2020-04-19' '2020-05-06' '2020-02-21' '2022-08-01' '2021-07-27'
 '2021-02-02' '2022-06-24' '2021-02-27' '2022-05-28' '2020-07-28'
 '2021-09-04' '2022-11-06' '2021-01-01' '2020-11-18' '2022-08-20'
 '2020-03-26' '2021-07-09' '2022-03-18' '2020-09-26' '2020-09-12'
 '2022-03-17' '2020-03-07' '2022-06-16' '2022-11-27' '2020-07-01'
 '2022-04-15' '2020-09-18' '2020-08-21' '2020-08-27' '2022-04-08'
 '2020-05-09' '2020-09-10' '2020-09-30' '2021-06-21' '2021-05-19'
 '2022-09-25' '2020-10-10']

➡ months_listed (112 unique values):
[ 5.4  6.3  6.9  6.1  8.7  5.1  nan  5.8  4.4  3.   4.6  3.7  6.2  5.3
  3.5  5.   5.5  7.8  4.9  4.7  8.9  5.9  3.8  4.8  7.6  6.4  7.9  6.6
  4.1  7.4  7.1  6.7  3.9  4.3  8.1  6.5  7.7  5.2  2.6  4.2  1.2  8.
  5.6  3.3  7.3  9.4  8.8  6.   3.6  3.2  8.5  4.5 10.4  9.2  1.7 10.2
  0.8  5.7  2.   2.3  8.6  7.5  9.6  9.7  6.8  2.2  2.5  4.   8.3 10.7
  2.7  3.4  7.   9.1  2.8  8.2 11.4 10.   2.9 10.1  7.2 10.5  9.9  3.1
  9.3  9.   1.3  8.4 11.   1.9 12.3  9.5  2.1  9.8  2.4  0.5 11.5  1.8
  1.6  1.5 10.8  1.4 11.6 10.3 10.6  0.6 11.3 11.7 11.8  1.1  1.  10.9]

➡ bedrooms (5 unique values):
[2 5 6 4 3]

➡ house_type (6 unique values):
['Semi-detached' 'Detached' 'Det.' 'Terraced' 'Semi' 'Terr.']

➡ area (1282 unique values):
['107.8 sq.m.' '498.8 sq.m.' '542.5 sq.m.' ... '432.2 sq.m.' '253.7 sq.m.'
 '268.7 sq.m.']

# Task 1

The team at RealAgents knows that the city that a property is located in makes a difference to the sale price. 

Unfortuntately they believe that this isn't always recorded in the data. 

Calculate the number of missing values of the `city`. 

 - You should use the data in the file "house_sales.csv". 

 - Your output should be an object `missing_city`, that contains the number of missing values in this column.

In [34]:
# Use this cell to write your code for Task 1

import numpy as np

# Replace '--' with NaN in the 'city' column
df['city'].replace('--', np.nan, inplace=True)

# Count missing values in the 'city' column
missing_city = df['city'].isna().sum()

# Print the result
print("Number of missing values in 'city':", missing_city)

Number of missing values in 'city': 73

# Task 2 

Before you fit any models, you will need to make sure the data is clean. 

The table below shows what the data should look like. 

Create a cleaned version of the dataframe. 

 - You should start with the data in the file "house_sales.csv". 

 - Your output should be a dataframe named `clean_data`. 

 - All column names and values should match the table below.


| Column Name | Criteria                                                |
|-------------|---------------------------------------------------------|
| house_id    | Nominal. </br> Unique identifier for houses. </br>Missing values not possible. |
| city        | Nominal. </br>The city in which the house is located. One of 'Silvertown', 'Riverford', 'Teasdale' and 'Poppleton' </br>Replace missing values with "Unknown". |
| sale_price  | Discrete. </br>The sale price of the house in whole dollars. Values can be any positive number greater than or equal to zero.</br>Remove missing entries. |
| sale_date   | Discrete. </br>The date of the last sale of the house. </br>Replace missing values with 2023-01-01. |
| months_listed  | Continuous. </br>The number of months the house was listed on the market prior to its last sale, rounded to one decimal place. </br>Replace missing values with mean number of months listed, to one decimal place. |
| bedrooms    | Discrete. </br>The number of bedrooms in the house. Any positive values greater than or equal to zero. </br>Replace missing values with the mean number of bedrooms, rounded to the nearest integer. |
| house_type   | Ordinal. </br>One of "Terraced", "Semi-detached", or "Detached". </br>Replace missing values with the most common house type. |
| area      | Continuous. </br>The area of the house in square meters, rounded to one decimal place. </br>Replace missing values with the mean, to one decimal place. |

In [35]:
# Use this cell to write your code for Task 2

# Replace missing 'city' with 'Unknown'
df['city'].fillna("Unknown", inplace=True)

# Drop rows with missing sale_price
df.dropna(subset=['sale_price'], inplace=True)

# Replace missing sale_date with default date
df['sale_date'].fillna("2023-01-01", inplace=True)

# Fill missing months_listed with mean (rounded to 1 decimal)
df['months_listed'].fillna(df['months_listed'].mean().round(1), inplace=True)

# Fill missing bedrooms with mean (rounded to nearest integer)
df['bedrooms'].fillna(round(df['bedrooms'].mean()), inplace=True)

# Standardize house_type labels
df['house_type'].replace({
    'Det.': 'Detached',
    'Terr.': 'Terraced',
    'Semi': 'Semi-detached'
}, inplace=True)

# Fill missing house_type with most frequent value
df['house_type'].fillna(df['house_type'].mode()[0], inplace=True)

# Convert 'area' column from string to float (remove ' sq.m.')
df['area'] = df['area'].str.replace(' sq.m.', '', regex=False).astype(float)

# Fill missing area with mean (rounded to 1 decimal)
df['area'].fillna(df['area'].mean().round(1), inplace=True)

# Final clean dataframe
clean_data = df.copy()

print(clean_data)

      house_id        city  sale_price  ... bedrooms     house_type   area
0      1217792  Silvertown       55943  ...        2  Semi-detached  107.8
1      1900913  Silvertown      384677  ...        5       Detached  498.8
2      1174927   Riverford      281707  ...        6       Detached  542.5
3      1773666  Silvertown      373251  ...        6       Detached  528.4
4      1258487  Silvertown      328885  ...        5       Detached  477.1
...        ...         ...         ...  ...      ...            ...    ...
1495   1123892   Riverford      198661  ...        5       Detached  432.2
1496   1327295   Poppleton      358304  ...        6       Detached  599.8
1497   1058161   Riverford      176612  ...        4       Detached  359.1
1498   1822037    Teasdale      197827  ...        3       Detached  253.7
1499   1679272   Poppleton      162099  ...        3       Detached  268.7

[1500 rows x 8 columns]

In [36]:
for col in df.columns:
    unique_vals = clean_data[col].unique()
    print(f"\n➡ {col} ({len(unique_vals)} unique values):")
    print(unique_vals)

➡ house_id (1500 unique values):
[1217792 1900913 1174927 ... 1058161 1822037 1679272]

➡ city (5 unique values):
['Silvertown' 'Riverford' 'Teasdale' 'Poppleton' 'Unknown']

➡ sale_price (1499 unique values):
[ 55943 384677 281707 ... 176612 197827 162099]

➡ sale_date (817 unique values):
['2021-09-12' '2021-01-17' '2021-11-10' '2020-04-13' '2020-09-24'
 '2020-09-25' '2021-05-18' '2020-10-15' '2021-01-07' '2020-05-04'
 '2021-10-26' '2020-06-11' '2022-10-10' '2021-08-04' '2020-08-18'
 '2021-07-18' '2020-11-23' '2020-06-05' '2020-11-19' '2020-02-25'
 '2020-04-16' '2020-01-14' '2022-12-28' '2020-04-07' '2020-01-09'
 '2021-08-29' '2022-05-20' '2021-12-13' '2020-10-27' '2022-08-22'
 '2022-11-14' '2021-04-02' '2020-01-31' '2020-09-29' '2022-09-05'
 '2020-07-23' '2020-10-14' '2020-08-03' '2020-07-05' '2022-04-03'
 '2022-01-14' '2021-03-19' '2022-04-29' '2022-10-16' '2022-08-02'
 '2021-09-30' '2021-09-07' '2022-07-30' '2022-01-03' '2020-12-27'
 '2020-06-15' '2022-09-07' '2022-09-17' '2022-09-23' '2021-06-05'
 '2022-08-06' '2022-05-10' '2021-02-28' '2020-06-27' '2020-10-06'
 '2022-12-18' '2021-12-22' '2022-12-19' '2021-07-31' '2020-09-28'
 '2022-05-16' '2022-10-02' '2021-05-23' '2020-11-13' '2020-03-08'
 '2021-11-06' '2022-02-04' '2020-06-04' '2022-10-03' '2021-04-20'
 '2022-02-25' '2020-06-18' '2020-05-28' '2020-12-28' '2021-02-13'
 '2021-05-14' '2021-10-11' '2020-06-24' '2021-02-24' '2021-06-04'
 '2022-02-11' '2020-06-03' '2022-03-10' '2020-07-11' '2022-07-08'
 '2021-11-09' '2021-12-04' '2020-07-16' '2021-09-15' '2021-04-24'
 '2021-03-18' '2020-04-10' '2022-11-28' '2021-08-11' '2021-05-28'
 '2021-01-27' '2020-12-25' '2021-10-07' '2022-06-14' '2020-07-14'
 '2020-05-16' '2020-09-13' '2022-02-26' '2022-07-27' '2021-07-23'
 '2020-12-22' '2021-06-06' '2021-01-09' '2022-10-05' '2020-02-07'
 '2022-02-22' '2021-01-19' '2021-02-20' '2020-01-17' '2021-04-30'
 '2021-07-04' '2021-08-06' '2020-11-26' '2022-12-10' '2020-11-06'
 '2022-05-18' '2022-08-03' '2020-02-13' '2021-08-14' '2020-06-09'
 '2021-02-19' '2020-01-10' '2022-09-21' '2022-12-21' '2021-01-10'
 '2021-09-16' '2020-01-07' '2020-06-29' '2022-01-08' '2020-01-22'
 '2020-07-27' '2022-10-14' '2020-10-08' '2020-10-07' '2022-04-04'
 '2022-02-23' '2022-06-20' '2022-07-12' '2022-01-10' '2022-02-10'
 '2022-04-16' '2020-01-15' '2021-02-14' '2022-04-09' '2021-03-01'
 '2020-09-08' '2022-07-20' '2020-10-01' '2020-12-14' '2021-08-30'
 '2020-04-12' '2020-01-16' '2022-11-26' '2020-08-09' '2022-12-16'
 '2021-12-24' '2022-03-29' '2021-04-17' '2021-10-12' '2022-03-03'
 '2022-09-02' '2021-08-28' '2021-08-18' '2021-03-13' '2022-07-19'
 '2020-04-23' '2022-01-17' '2022-03-14' '2022-09-30' '2022-01-20'
 '2022-06-18' '2021-06-25' '2022-06-15' '2022-01-25' '2021-07-15'
 '2021-09-24' '2021-03-09' '2020-11-10' '2021-12-21' '2020-06-28'
 '2021-03-14' '2020-02-20' '2022-08-05' '2020-02-15' '2021-04-27'
 '2022-05-05' '2022-11-13' '2020-08-10' '2022-12-13' '2021-11-26'
 '2022-12-29' '2021-10-18' '2020-07-30' '2022-10-17' '2022-06-10'
 '2021-02-07' '2021-01-22' '2020-08-20' '2021-01-25' '2022-10-01'
 '2022-08-07' '2022-08-18' '2021-05-10' '2020-03-22' '2021-06-03'
 '2022-12-11' '2021-11-24' '2022-12-01' '2022-12-05' '2020-02-09'
 '2021-01-05' '2021-02-25' '2022-09-26' '2020-03-15' '2021-01-16'
 '2022-11-23' '2020-05-17' '2021-12-07' '2020-08-15' '2021-10-30'
 '2021-05-24' '2022-01-05' '2021-12-09' '2021-07-10' '2020-04-29'
 '2020-11-14' '2022-03-07' '2020-02-19' '2020-03-24' '2021-11-01'
 '2021-05-13' '2022-06-28' '2020-09-16' '2021-06-14' '2021-05-17'
 '2020-01-12' '2021-08-21' '2022-09-15' '2021-11-12' '2021-02-04'
 '2021-12-01' '2021-03-20' '2022-11-07' '2022-09-28' '2022-05-26'
 '2022-10-24' '2021-07-11' '2020-03-27' '2022-01-12' '2022-06-17'
 '2020-04-30' '2022-10-04' '2021-01-20' '2020-03-17' '2020-07-22'
 '2022-11-12' '2020-03-09' '2022-12-30' '2021-10-21' '2021-12-11'
 '2022-07-28' '2021-08-23' '2022-12-22' '2022-07-16' '2020-05-15'
 '2020-12-31' '2022-10-18' '2022-08-30' '2022-09-29' '2020-08-06'
 '2022-05-13' '2020-06-14' '2021-09-13' '2020-04-08' '2022-06-08'
 '2020-02-08' '2021-07-07' '2022-05-04' '2020-07-06' '2021-09-08'
 '2021-04-11' '2021-11-21' '2021-08-31' '2020-10-16' '2022-12-24'
 '2021-03-31' '2021-05-01' '2021-01-21' '2020-05-10' '2020-04-05'
 '2020-04-17' '2020-03-06' '2022-09-01' '2020-02-12' '2020-08-25'
 '2021-12-23' '2021-08-05' '2020-05-07' '2022-05-02' '2020-07-12'
 '2020-01-27' '2020-04-21' '2022-03-28' '2021-04-12' '2021-06-13'
 '2022-01-22' '2021-06-17' '2020-08-26' '2021-09-27' '2022-02-17'
 '2021-09-06' '2020-08-08' '2020-11-21' '2021-05-21' '2020-10-17'
 '2020-03-19' '2021-10-24' '2020-02-27' '2022-04-02' '2021-02-01'
 '2021-08-24' '2021-10-25' '2021-11-20' '2021-06-20' '2020-07-31'
 '2020-12-24' '2021-08-19' '2022-05-27' '2022-06-11' '2021-10-29'
 '2020-08-17' '2021-11-25' '2021-07-01' '2020-01-03' '2022-01-29'
 '2022-04-17' '2020-11-04' '2022-07-23' '2022-07-11' '2022-12-15'
 '2020-12-01' '2021-02-26' '2020-11-25' '2020-11-16' '2020-03-18'
 '2021-12-28' '2020-07-07' '2021-11-03' '2021-12-06' '2021-05-31'
 '2022-11-01' '2021-06-30' '2022-12-20' '2020-11-29' '2022-06-04'
 '2020-10-20' '2022-02-27' '2020-07-26' '2021-08-15' '2022-09-14'
 '2021-10-20' '2021-06-12' '2021-01-04' '2021-08-07' '2020-11-11'
 '2020-11-08' '2022-11-08' '2020-01-01' '2021-04-08' '2021-01-08'
 '2021-01-26' '2021-09-23' '2022-04-11' '2020-10-26' '2020-12-29'
 '2020-04-27' '2021-03-10' '2022-05-15' '2020-01-30' '2020-01-06'
 '2020-06-13' '2021-08-26' '2020-05-24' '2020-08-22' '2020-09-04'
 '2022-11-10' '2021-09-19' '2021-06-11' '2022-03-25' '2022-02-13'
 '2022-01-31' '2022-10-09' '2020-06-06' '2021-01-14' '2022-06-07'
 '2020-12-12' '2022-10-26' '2020-01-28' '2022-03-08' '2021-10-23'
 '2021-08-01' '2020-08-31' '2020-04-18' '2020-03-02' '2021-02-15'
 '2020-09-19' '2020-02-17' '2022-03-31' '2021-05-08' '2021-12-31'
 '2022-10-19' '2022-04-01' '2021-07-22' '2022-10-11' '2021-02-06'
 '2021-06-24' '2020-05-29' '2022-10-29' '2020-12-26' '2022-08-29'
 '2020-01-19' '2020-06-08' '2022-09-10' '2022-02-15' '2020-03-20'
 '2020-09-02' '2020-03-31' '2022-05-29' '2021-05-29' '2022-08-04'
 '2021-03-15' '2022-05-11' '2020-03-01' '2022-05-30' '2022-01-04'
 '2021-07-26' '2021-11-29' '2022-08-08' '2021-11-17' '2020-10-09'
 '2021-06-09' '2021-06-18' '2020-09-05' '2021-06-16' '2020-12-09'
 '2022-03-22' '2022-01-26' '2021-10-17' '2022-12-25' '2020-02-28'
 '2020-12-07' '2020-11-27' '2022-04-28' '2021-04-03' '2021-04-15'
 '2021-09-11' '2022-04-27' '2022-06-25' '2022-11-25' '2021-10-19'
 '2021-03-08' '2022-12-26' '2022-01-11' '2021-05-11' '2021-07-19'
 '2020-06-25' '2020-09-15' '2022-02-28' '2020-01-08' '2020-01-02'
 '2021-04-01' '2020-03-13' '2022-09-09' '2022-05-31' '2021-03-05'
 '2021-09-22' '2020-12-17' '2020-08-11' '2022-09-16' '2022-07-09'
 '2022-05-14' '2021-12-03' '2021-07-08' '2020-05-20' '2022-02-01'
 '2022-03-06' '2022-04-06' '2022-02-16' '2020-11-24' '2021-04-29'
 '2021-11-11' '2020-04-28' '2021-01-02' '2022-07-13' '2021-07-02'
 '2022-04-24' '2021-05-04' '2020-10-13' '2021-12-14' '2022-02-20'
 '2020-10-30' '2020-11-05' '2020-03-04' '2020-11-30' '2022-08-19'
 '2021-03-02' '2021-10-06' '2020-12-11' '2021-02-11' '2020-08-12'
 '2021-04-04' '2020-11-15' '2022-02-05' '2021-03-17' '2022-03-23'
 '2022-03-16' '2021-11-19' '2020-05-13' '2020-12-03' '2022-03-15'
 '2021-11-28' '2021-03-29' '2020-02-11' '2021-03-25' '2021-11-13'
 '2022-03-27' '2020-07-24' '2020-12-06' '2021-07-21' '2021-06-27'
 '2020-01-13' '2021-08-27' '2021-11-30' '2020-03-03' '2021-08-03'
 '2022-12-17' '2021-09-01' '2020-04-03' '2022-01-19' '2022-07-24'
 '2021-02-16' '2022-09-03' '2022-03-21' '2022-10-30' '2020-07-29'
 '2021-05-12' '2020-03-23' '2021-10-27' '2022-12-14' '2021-04-21'
 '2022-05-24' '2021-09-05' '2021-04-18' '2021-02-03' '2022-09-22'
 '2022-06-22' '2021-01-31' '2022-03-20' '2022-11-18' '2022-05-17'
 '2022-04-23' '2020-01-05' '2020-09-07' '2021-10-03' '2020-10-31'
 '2021-06-01' '2022-04-21' '2022-04-14' '2022-01-01' '2021-03-24'
 '2020-06-10' '2020-06-23' '2021-12-25' '2021-07-14' '2021-09-09'
 '2021-05-25' '2021-10-02' '2021-10-09' '2021-06-23' '2020-11-02'
 '2020-08-01' '2022-03-24' '2021-12-19' '2021-07-20' '2022-06-27'
 '2020-04-24' '2022-11-03' '2020-07-08' '2020-03-21' '2021-07-30'
 '2022-11-20' '2020-08-04' '2021-01-28' '2022-04-19' '2022-04-13'
 '2022-10-27' '2020-06-19' '2020-01-23' '2020-05-31' '2020-02-03'
 '2022-07-29' '2022-04-07' '2021-11-15' '2022-02-06' '2022-10-08'
 '2021-12-12' '2022-06-26' '2021-10-13' '2020-12-15' '2021-06-26'
 '2020-05-14' '2022-02-19' '2020-10-25' '2021-10-28' '2020-10-21'
 '2022-11-19' '2022-04-22' '2022-11-15' '2022-06-19' '2020-08-16'
 '2021-07-16' '2021-09-20' '2021-09-29' '2021-10-04' '2020-12-30'
 '2020-03-05' '2021-12-27' '2022-10-22' '2020-11-12' '2022-04-05'
 '2022-07-04' '2020-05-12' '2022-09-08' '2022-11-11' '2022-05-08'
 '2021-06-19' '2021-05-30' '2020-07-20' '2022-05-25' '2022-09-04'
 '2021-07-24' '2020-09-27' '2021-05-27' '2022-10-23' '2021-07-12'
 '2021-06-29' '2021-12-20' '2020-01-20' '2021-05-16' '2021-07-03'
 '2020-08-30' '2020-10-11' '2020-05-19' '2022-07-10' '2022-06-03'
 '2020-04-09' '2021-11-14' '2022-04-18' '2020-10-03' '2022-02-12'
 '2022-04-30' '2021-10-16' '2021-04-22' '2022-10-12' '2022-12-08'
 '2021-09-14' '2022-12-06' '2022-10-20' '2020-02-06' '2021-01-15'
 '2020-11-09' '2021-09-28' '2020-02-22' '2021-05-22' '2022-07-17'
 '2022-10-06' '2021-02-23' '2022-12-23' '2020-09-17' '2020-07-03'
 '2021-10-14' '2020-07-19' '2021-08-20' '2021-04-14' '2021-04-06'
 '2022-07-03' '2022-07-01' '2022-11-29' '2022-10-21' '2021-07-29'
 '2020-04-11' '2021-08-25' '2020-05-23' '2020-07-21' '2022-08-11'
 '2021-01-12' '2021-03-23' '2020-04-14' '2021-11-23' '2021-03-11'
 '2020-03-12' '2021-10-10' '2021-06-28' '2020-07-10' '2022-02-08'
 '2021-09-17' '2021-08-08' '2020-02-29' '2020-10-24' '2022-06-13'
 '2021-04-05' '2022-03-02' '2022-09-24' '2022-03-13' '2022-10-31'
 '2022-07-18' '2022-06-01' '2021-09-10' '2020-08-02' '2020-02-04'
 '2022-08-25' '2022-01-16' '2021-12-10' '2021-12-29' '2022-10-25'
 '2021-12-17' '2022-05-06' '2022-07-14' '2020-02-26' '2020-04-20'
 '2020-07-15' '2022-01-27' '2021-01-06' '2020-11-17' '2022-04-10'
 '2020-05-08' '2021-04-09' '2022-08-28' '2020-03-16' '2022-04-12'
 '2021-01-11' '2022-09-13' '2022-11-22' '2022-06-30' '2021-08-17'
 '2021-11-18' '2021-09-21' '2021-01-18' '2022-09-18' '2020-07-25'
 '2020-01-26' '2021-10-22' '2020-08-13' '2021-11-05' '2020-11-22'
 '2022-05-23' '2020-12-13' '2022-08-31' '2021-05-26' '2020-09-14'
 '2021-07-13' '2021-05-02' '2020-05-02' '2022-01-24' '2022-12-12'
 '2020-08-24' '2020-11-01' '2022-08-24' '2021-11-27' '2022-10-13'
 '2020-04-19' '2020-05-06' '2020-02-21' '2022-08-01' '2021-07-27'
 '2021-02-02' '2022-06-24' '2021-02-27' '2022-05-28' '2020-07-28'
 '2021-09-04' '2022-11-06' '2021-01-01' '2020-11-18' '2022-08-20'
 '2020-03-26' '2021-07-09' '2022-03-18' '2020-09-26' '2020-09-12'
 '2022-03-17' '2020-03-07' '2022-06-16' '2022-11-27' '2020-07-01'
 '2022-04-15' '2020-09-18' '2020-08-21' '2020-08-27' '2022-04-08'
 '2020-05-09' '2020-09-10' '2020-09-30' '2021-06-21' '2021-05-19'
 '2022-09-25' '2020-10-10']

➡ months_listed (111 unique values):
[ 5.4  6.3  6.9  6.1  8.7  5.1  5.9  5.8  4.4  3.   4.6  3.7  6.2  5.3
  3.5  5.   5.5  7.8  4.9  4.7  8.9  3.8  4.8  7.6  6.4  7.9  6.6  4.1
  7.4  7.1  6.7  3.9  4.3  8.1  6.5  7.7  5.2  2.6  4.2  1.2  8.   5.6
  3.3  7.3  9.4  8.8  6.   3.6  3.2  8.5  4.5 10.4  9.2  1.7 10.2  0.8
  5.7  2.   2.3  8.6  7.5  9.6  9.7  6.8  2.2  2.5  4.   8.3 10.7  2.7
  3.4  7.   9.1  2.8  8.2 11.4 10.   2.9 10.1  7.2 10.5  9.9  3.1  9.3
  9.   1.3  8.4 11.   1.9 12.3  9.5  2.1  9.8  2.4  0.5 11.5  1.8  1.6
  1.5 10.8  1.4 11.6 10.3 10.6  0.6 11.3 11.7 11.8  1.1  1.  10.9]

➡ bedrooms (5 unique values):
[2 5 6 4 3]

➡ house_type (3 unique values):
['Semi-detached' 'Detached' 'Terraced']

➡ area (1282 unique values):
[107.8 498.8 542.5 ... 432.2 253.7 268.7]

In [37]:
print(clean_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   house_id       1500 non-null   int64
 1   city           1500 non-null   object
 2   sale_price     1500 non-null   int64
 3   sale_date      1500 non-null   object
 4   months_listed  1500 non-null   float64
 5   bedrooms       1500 non-null   int64
 6   house_type     1500 non-null   object
 7   area           1500 non-null   float64
dtypes: float64(2), int64(3), object(3)
memory usage: 93.9+ KB
None

# Task 3 

The team at RealAgents have told you that they have always believed that the number of bedrooms is the biggest driver of house price. 

Producing a table showing the difference in the average sale price by number of bedrooms along with the variance to investigate this question for the team.

 - You should start with the data in the file 'house_sales.csv'.

 - Your output should be a data frame named `price_by_rooms`. 

 - It should include the three columns `bedrooms`, `avg_price`, `var_price`. 

 - Your answers should be rounded to 1 decimal place.

In [38]:
# Use this cell to write your code for Task 3

# Load and clean data again (in case you're starting fresh)
df = pd.read_csv("house_sales.csv", na_values=["--"])

# Clean data (same as before)
df['city'].fillna("Unknown", inplace=True)
df.dropna(subset=['sale_price'], inplace=True)
df['sale_date'].fillna("2023-01-01", inplace=True)
df['months_listed'].fillna(df['months_listed'].mean().round(1), inplace=True)
df['bedrooms'].fillna(round(df['bedrooms'].mean()), inplace=True)
df['house_type'].replace({'Det.': 'Detached', 'Terr.': 'Terraced', 'Semi': 'Semi-detached'}, inplace=True)
df['house_type'].fillna(df['house_type'].mode()[0], inplace=True)
df['area'] = df['area'].str.replace(' sq.m.', '', regex=False).astype(float)
df['area'].fillna(df['area'].mean().round(1), inplace=True)

#  Group by bedrooms and calculate average and variance
price_by_rooms = df.groupby('bedrooms')['sale_price'].agg(
    avg_price=lambda x: round(x.mean(), 1),
    var_price=lambda x: round(x.var(), 1)
).reset_index()

# Show the result
print(price_by_rooms)

   bedrooms  avg_price     var_price
0         2    67076.4  5.652896e+08
1         3   154665.1  2.378289e+09
2         4   234704.6  1.725211e+09
3         5   301515.9  2.484328e+09
4         6   375741.3  3.924432e+09

# Task 4

Fit a baseline model to predict the sale price of a house.

 1. Fit your model using the data contained in “train.csv” </br></br>

 2. Use “validation.csv” to predict new values based on your model. You must return a dataframe named `base_result`, that includes `house_id` and `price`. The price column must be your predicted values.

In [39]:
# Use this cell to write your code for Task 4

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Load train and validation data
train = pd.read_csv("train.csv", na_values=["--"])
validation = pd.read_csv("validation.csv", na_values=["--"])

# Clean both datasets
for df in [train, validation]:
    df['city'].fillna("Unknown", inplace=True)
    df['sale_date'].fillna("2023-01-01", inplace=True)
    df['months_listed'].fillna(df['months_listed'].mean().round(1), inplace=True)
    df['bedrooms'].fillna(round(df['bedrooms'].mean()), inplace=True)
    df['house_type'].replace({'Det.': 'Detached', 'Terr.': 'Terraced', 'Semi': 'Semi-detached'}, inplace=True)
    df['house_type'].fillna(df['house_type'].mode()[0], inplace=True)
    df['area'] = pd.to_numeric(df['area'].astype(str).str.replace(' sq.m.', '', regex=False), errors='coerce')
    df['area'].fillna(df['area'].mean().round(1), inplace=True)

# Define features and target
X_train = train.drop(columns=['house_id', 'sale_price', 'sale_date'])
y_train = train['sale_price']

X_valid = validation.drop(columns=['house_id', 'sale_date'])

# Define categorical columns
categorical_cols = X_train.select_dtypes(include='object').columns.tolist()

# Preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ],
    remainder='passthrough'
)

# Full pipeline with model
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

# Fit model
model.fit(X_train, y_train)

# Predict on validation set
predictions = model.predict(X_valid)

# Create result dataframe
base_result = validation[['house_id']].copy()
base_result['price'] = predictions

# Show first few rows
print(base_result.head())

   house_id          price
0   1331375  121527.827316
1   1630115  304386.625267
2   1645745  384760.100656
3   1336775  123976.268985
4   1888274  271186.199353

# Task 5

Fit a comparison model to predict the sale price of a house.

 1. Fit your model using the data contained in “train.csv” </br></br>

 2. Use “validation.csv” to predict new values based on your model. You must return a dataframe named `compare_result`, that includes `house_id` and `price`. The price column must be your predicted values.

In [40]:
# Use this cell to write your code for Task 5

import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Load training and validation datasets
train = pd.read_csv("train.csv", na_values=["--"])
validation = pd.read_csv("validation.csv", na_values=["--"])

# Data cleaning
for df in [train, validation]:
    df['city'].fillna("Unknown", inplace=True)
    df['sale_date'].fillna("2023-01-01", inplace=True)
    df['months_listed'].fillna(df['months_listed'].mean().round(1), inplace=True)
    df['bedrooms'].fillna(round(df['bedrooms'].mean()), inplace=True)
    df['house_type'].replace({'Det.': 'Detached', 'Terr.': 'Terraced', 'Semi': 'Semi-detached'}, inplace=True)
    df['house_type'].fillna(df['house_type'].mode()[0], inplace=True)
    if df['area'].dtype == 'object':
        df['area'] = df['area'].str.replace(' sq.m.', '', regex=False).astype(float)
    df['area'].fillna(df['area'].mean().round(1), inplace=True)

# Features and target
X_train = train.drop(columns=['house_id', 'sale_price', 'sale_date'])
y_train = train['sale_price']
X_valid = validation.drop(columns=['house_id', 'sale_date'])

# Categorical columns
categorical_cols = X_train.select_dtypes(include='object').columns.tolist()

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ],
    remainder='passthrough'
)

# Pipeline with RandomForestRegressor
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(n_estimators=100, random_state=42))
])

# Fit the model
model.fit(X_train, y_train)

# Predict on validation data
validation['price'] = model.predict(X_valid)

# Prepare compare_result
compare_result = validation[['house_id', 'price']].copy()

# Show result
print(compare_result.head())

   house_id      price
0   1331375   82582.62
1   1630115  303256.87
2   1645745  404809.08
3   1336775  106624.68
4   1888274  267768.22